[build]
  command = "npm run build"
  publish = "dist"

# Remove or comment out any [[plugins]] section that references "@netlify/plugin-nextjs"
# If you don't have other plugins, you can simply not have a [[plugins]] section at all.
# If you DO have other plugins, make sure the Next.js one is specifically excluded.
# Example of what to remove:
# [[plugins]]
#   package = "@netlify/plugin-nextjs"
#   # any other lines related to this plugin